### ISSUE TITLE
Trouble finding the exe to download

### ISSUE THREAD

**Issue by majinsnake** [KevGreenwood/OpenFuryKMS#1]
Downloaded the whole code and searched it on the website. I could not find the exe file. Please assist.

**Comment by KevGreenwood** [comment]
> Downloaded the whole code and searched it on the website. I could not find the exe file. Please assist.

Hi majinsnake, to download my program you must go to the Releases section and select the version according to the bitness of your operating system, in my case, my system is 64-bit, so I downloaded the x64 version.
![Captura de pantalla 2024-04-25 080529](https://github.com/KevGreenwood/OpenFuryKMS/assets/159276447/4f80f4b2-6d6f-428e-b650-517557d23b3b)
